- name : variable script
  hosts: node
  vars:
    tool_name: "Ansible"
    Duration: "one week"

  tasks:
  - name : checking the varibales
    ansible.builtin.debug:
      msg: "Hi, This is the prcticing of tools {{tool_name}}, for which it will take time {{Duration}}"

