- name : variable script
  hosts: node
  vars:
    tool_name: "Ansible"
    Duration: "one week"

  tasks:
  - name: override variables
    set_fact:
      tool_name: "AWS"
      Duration: "4 weeks"

  - name : checking the variables
    ansible.builtin.debug:
      msg: "Hi, This is the practicing of tools {{tool_name}}, for which it will take time {{Duration}}"
