---
 - name: copy the files with in the remote servers
   hosts: all
   become: yes
   tasks:
    - name: creating the file in the remote servers
      ansible.builtin.file:
        path: /etc/test_file_1.yaml
        state: touch

    - name: copying file from one loaction to another location
      ansible.builtin.copy:
        src: /etc/test_file_1.yaml
        dest: /tmp/test_file_1.yaml
        remote_src: yes