---
- name: uninstalling all the packages
  hosts: all
  become: yes
  tasks: 
    - name : list of packages
      ansible.builtin.package:
       name: "{{ item }}"
       state: absent
      loop:
        - vim
        - git
        - nginx
        - htop
        - curl
      ignore_errors: yes
      loop_control: 
       label: Uninstalling the packages {{ item }}
